function visualize(handles, message, progress, eegRun)
    frequenciesToPlot   = [8 12; 12 16; 16 20; 20 28]; %Hz
    %% Visualization
    message{4} = 'Visualizing';
    set(handles.log, 'String', message);
    handles.bar.update(progress.current + progress.step * 1);

    if get(handles.topoplot, 'Value') == 1
        EEGDisplayer.topoplotPSDOfTwoClasses(nanmean(eegRun.mvt,2), ...
            nanmean(eegRun.rest,2), ...
            eegRun.spectProperties.frequencies, ...
            frequenciesToPlot, ...
            eegRun.channelsData64, ...
            eegRun.labels)
    end
    if get(handles.spectrogram, 'Value') == 1
        baseline = eegRun.getSpecificEventTypeTimes(eegRun.uniqueEvents.Baseline, eegRun.uniqueEvents.Baseline,1);
        trialStart = eegRun.getSpecificEventTypeTimes(eegRun.uniqueEvents.Baseline, eegRun.uniqueEvents.Start,1);
        events = horzcat(baseline, trialStart);
        eventLabels = {'Baseline', 'Start'};
        SpectrogramDisplayer().plotSpectrogramForTwoClasses(...
            squeeze(nanmean(eegRun.spectMvt,2)),...
            squeeze(nanmean(eegRun.spectRest,2)), ...
            eegRun.spectProperties, ...
            {eegRun.channelsData.labels},...
            events,...
            eventLabels,...
            eegRun.labels);
    end
    if get(handles.discriminancyMap, 'Value') == 1
        EEGDisplayer().displayDiscriminancyMap(eegRun);
    end
end